server:
  name: quarts-intro
  port: 80

quartz:
    jobStore:
      #The database name to be used to create the quartz scheduler specific collections.
      dbName: ${MONGODB_DATABASE}
      
spring:
  data:
    mongodb:
      host: ${MONGODB_HOST}
      username: ${MONGODB_USER}
      password: ${MONGODB_PASSWORD}
      database: ${MONGODB_DATABASE}
      port: ${MONGODB_PORT}

  #profiles:
  #  active: dev